"""Add created_at and deleted_at to drivers

Revision ID: 92edf2f2eae1
Revises: 3853e6074992
Create Date: 2025-03-30 19:19:34.749943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92edf2f2eae1'
down_revision: Union[str, None] = '3853e6074992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('drivers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'deleted_at')
    op.drop_column('drivers', 'created_at')
    # ### end Alembic commands ###
